### ISSUE TITLE
Redir after login

### ISSUE THREAD

**Issue by ondrejvysek** [trilbymedia/grav-plugin-login-oauth2-extras#2]
Configured the plugin without any issues for the admin. When using OAuth for the admin access, I'm redirected to /1 page (which obviously doesn't exist). When I enter /admin everything I'm logged in.

The same result e.g. with facebook, it is redirecting to /1#_=_

is there anything more needs to be configured?

**Comment by rhukster** [comment]
I think you need to set the login route in the login plugin.

**Comment by ondrejvysek** [comment]
wow, that's the magic :) never played with the login config before as I'm using login just for the admin - disabled redirect after login completely and now it works as expected. 

Btw in the login plugin, there is just "After login route" not separated for the main site/frontend and admin. Make sense to redirect for the frontend but no reason to do for the /admin - as it always is /admin or better "Administrator path" in the Admin panel.
